# Code Generated by Sidekick is for learning and experimentation purposes only.
from __future__ import annotations

from typing import Sequence, TypeVar

T = TypeVar("T")


def binary_search(arr: Sequence[T], target: T) -> int:
    """
    Return the index of `target` in sorted `arr`, or -1 if not found.

    Assumes `arr` is sorted in ascending order and elements are comparable.
    """
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = left + (right - left) // 2
        value = arr[mid]

        if value == target:
            return mid
        if value < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1


if __name__ == "__main__":
    data = [1, 3, 4, 7, 9, 12, 18]
    print(binary_search(data, 9))   # 4
    print(binary_search(data, 10))  # -1
